[package]
name = "dataprism-ironcalc-plugin"
version = "0.1.0"
edition = "2021"
description = "DataPrism plugin for Excel-compatible formula engine powered by IronCalc"
license = "MIT"
authors = ["DataPrism Team"]

[lib]
crate-type = ["cdylib"]

[dependencies]
# Note: IronCalc is not yet available on crates.io, so we'll simulate it with similar functionality
# In a real implementation, this would be: ironcalc = { version = "0.4", default-features = false }

# WebAssembly bindings
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
js-sys = "0.3"
console_error_panic_hook = "0.1"

# Simulated formula engine (for this implementation)
# In production, this would be replaced with actual IronCalc
regex = "1.0"
chrono = { version = "0.4", features = ["serde"] }

[dependencies.web-sys]
version = "0.3"
features = [
  "File",
  "FileReader",
  "Blob", 
  "console",
  "Performance",
  "PerformanceEntry",
  "PerformanceTiming",
]

[dev-dependencies]
wasm-bindgen-test = "0.3"